// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Consumer
{
    public int Consumer_ID { get; set; }

    public string Surname { get; set; }

    public string Telephone { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string Home { get; set; }

    public virtual ICollection<Consumer_Product> Consumer_Products { get; set; } = new List<Consumer_Product>();

    public virtual ICollection<Order_Consumer> Order_Consumers { get; set; } = new List<Order_Consumer>();
}