// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Order_Consumer
{
    public int Order_Consumer_ID { get; set; }

    public int Order_ID { get; set; }

    public int Consumer_ID { get; set; }

    public virtual Consumer Consumer { get; set; }

    public virtual Order Order { get; set; }
}