// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Order
{
    public int Order_ID { get; set; }

    public int Product_ID { get; set; }

    public DateOnly Order_Date { get; set; }

    public DateTime Order_Completion_Date { get; set; }

    public virtual ICollection<Order_Consumer> Order_Consumers { get; set; } = new List<Order_Consumer>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}