// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Product
{
    public int Product_ID { get; set; }

    public string Product_Name { get; set; }

    public int Quantity { get; set; }

    public decimal Cost { get; set; }

    public DateOnly Delivery_Date { get; set; }

    public int? Order_ID { get; set; }

    public virtual ICollection<Consumer_Product> Consumer_Products { get; set; } = new List<Consumer_Product>();

    public virtual Order Order { get; set; }

    public virtual ICollection<Product_Warehouse_Supplier> Product_Warehouse_Suppliers { get; set; } = new List<Product_Warehouse_Supplier>();

    public virtual Supply Supply { get; set; }
}