// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Supply
{
    public int Supply_ID { get; set; }

    public int Product_ID { get; set; }

    public int Supplier_ID { get; set; }

    public string Unit_of_Measuring { get; set; }

    public double Tax { get; set; }

    public virtual Supplier Supply1 { get; set; }

    public virtual Product SupplyNavigation { get; set; }
}