// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Supplier
{
    public int Supplier_ID { get; set; }

    public string Company_Name { get; set; }

    public string Telephone { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string Home { get; set; }

    public string Surname_Director { get; set; }

    public virtual ICollection<Product_Warehouse_Supplier> Product_Warehouse_Suppliers { get; set; } = new List<Product_Warehouse_Supplier>();

    public virtual Supply Supply { get; set; }
}