// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class User
{
    public int User_ID { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }
}