// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UPpril.Models;

public partial class Warehouse
{
    public int Warehouse_ID { get; set; }

    public string Product_Name { get; set; }

    public string Unit_of_Measuring { get; set; }

    public int Quantity { get; set; }

    public virtual ICollection<Product_Warehouse_Supplier> Product_Warehouse_Suppliers { get; set; } = new List<Product_Warehouse_Supplier>();
}